### ISSUE TITLE
Using Gradle instead Maven

### ISSUE THREAD

**Issue by foxpluto** [mvysny/vaadin14-embedded-jetty-gradle#3]
Dear Sir,

sorry if I use the issue feature to write you but I am trying to convert your working example from maven to gradle and I am stuck with a problem which maybe you could help me with. 
I have pull your example and I have modified the project in this way: 
added a `build.gradle` configuration
```gradle
plugins {
    id 'java'
    id 'eclipse'
    id 'war'
    id 'org.gretty' version '3.0.3'
    id 'com.vaadin' version '0.8.0'
}

defaultTasks("clean", "build")

repositories {
    jcenter()
}

java {
    sourceCompatibility = JavaVersion.VERSION_11
    targetCompatibility = JavaVersion.VERSION_11
}

gretty {
    contextPath = "/"
    servletContainer = "jetty9.4"
}

// example of how to configure the Gradle Vaadin Plugin
vaadin {
    pnpmEnable = true
}

dependencies {
    implementation enforcedPlatform('com.vaadin:vaadin-bom:14.3.4')

    // Vaadin 14
    implementation("com.vaadin:vaadin-core") {
//         Webjars are only needed when running in Vaadin 13 compatibility mode
        ["com.vaadin.webjar", "org.webjars.bowergithub.insites",
         "org.webjars.bowergithub.polymer", "org.webjars.bowergithub.polymerelements",
         "org.webjars.bowergithub.vaadin", "org.webjars.bowergithub.webcomponents"]
                .forEach { group -> exclude(group: group) }
    }
    
    implementation "org.slf4j:slf4j-simple:1.7.30"

    implementation group: 'org.eclipse.jetty', name: 'jetty-server', version: '9.4.31.v20200723'
    implementation group: 'org.eclipse.jetty', name: 'jetty-servlet', version: '9.4.31.v20200723'
    implementation group: 'org.eclipse.jetty', name: 'jetty-webapp', version: '9.4.31.v20200723'
    implementation group: 'org.eclipse.jetty', name: 'jetty-annotations', version: '9.4.31.v20200723'
    implementation group: 'org.eclipse.jetty', name: 'jetty-plus', version: '9.4.31.v20200723'
    implementation group: 'org.eclipse.jetty', name: 'jetty-continuation', version: '9.4.31.v20200723'
    implementation group: 'org.eclipse.jetty.websocket', name: 'websocket-common', version: '9.4.31.v20200723'
    implementation group: 'org.eclipse.jetty.websocket', name: 'websocket-server', version: '9.4.31.v20200723'
    implementation group: 'org.eclipse.jetty.websocket', name: 'websocket-api', version: '9.4.31.v20200723'
    implementation group: 'org.eclipse.jetty.websocket', name: 'javax-websocket-server-impl', version: '9.4.31.v20200723'
    implementation group: 'javax.websocket', name: 'javax.websocket-client-api', version: '1.1'
    implementation group: 'javax.servlet', name: 'javax.servlet-api', version: '4.0.1'
    implementation group: 'org.apache.logging.log4j', name: 'log4j-core', version: '2.13.1'
    implementation group: 'org.apache.logging.log4j', name: 'log4j-api', version: '2.13.1'

    testImplementation group: 'junit', name: 'junit', version: '4.12'
}
```
Please note that I have included the Gradle Vaadin Plugin instead of the Maven one as indicated in the tutorial: [getting-started-gradle](https://vaadin.com/docs/flow/getting-started/getting-started-gradle.html).
Using the command `gradle appRun` the app works perfectly.
If I launch the main via the Visual Studio Code feature Jetty start but I have the error:
```
Could not navigate to ''
Reason: Couldn't find route for ''

Available routes:
This detailed message is only shown when running in development mode.
```
It seems to me that Jetty can't find the servlet. 

Do you have any idea how to debug this situation or point in the right direction? 

Sorry to bother you but I am really stuck here and I don't know how to ask help. 

Regards,
Stefano

**Comment by mvysny** [comment]
Dear Stefano,

the purpose of this project is to embed Jetty and runs itself. Therefore you're not supposed to use Gretty plugin at all with this project. In order to start the app from command-line please run:

```
./gradlew clean run
```

Since this project is not supposed to use Gretty, it will also not contain any Gretty-related tasks such as 'appRun' nor 'appStart'.

If you wish to use Gretty then please see a different example app: https://github.com/mvysny/karibu10-helloworld-application

**Comment by foxpluto** [comment]
Dear Mvysny,

thanks for your help, using gretty was just a test to try to understand.

You are right !!!!
If I run the application with:
```
./gradlew clean run
```
it actually start !!!
If I run the application in debug with Visual Studio Code `launch.json`
```
{
    // Use IntelliSense to learn about possible attributes.
    // Hover to view descriptions of existing attributes.
    // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
    "version": "0.2.0",
    "configurations": [
        {
            "type": "java",
            "name": "Vaadin",
            "request": "launch",
            "mainClass": "com.vaadin.starter.skeleton.ManualJetty",
            "projectName": "vaadin"
        }
    ]
}
```
it starts but no route are found.

Do you have any suggestion for me for trying to understand why? 
Anyway thanks very much for your help. 

Regards,
S.

**Comment by mvysny** [comment]
Unfortunately I haven't tried VS Code myself yet, so I'm not sure what might be the issue. For me the project is working fine in Intellij, but VS Code might be a bit different.

However, I think this issue was originally related to porting to Gradle from Maven and we wandered off the subject. I propose to close this issue; could you please open a new issue that the project is not working in VS Code?
