### ISSUE TITLE
Question: How can I configure an application name such as http://localhost:8080/erp

### ISSUE THREAD

**Issue by marcelbaumann** [mvysny/vaadin14-embedded-jetty-gradle#7]
Hello Martin

Thanks a lot for the provided example. I am using it for my vaadin application build with gradle and currently vaadin version 20.0.7.
It works great.

I am trying to configure the application so that the vaadin servlet will service _https://localhost:8080/erp_ instead of _http://localhost:8080_. (The idea is to later configure parallel access for a REST interface serviced under https://localhost:8080/api in the same web application).

I tried to configure the servlet path in the line _context.addServlet(VaadinServlet.class, "/*")_; but without any success (replacing "/*" with "/erp").

Do you have any ideas how I could do this? If I am successful, I would publish the solution with vaadin and REST services.
(I know I could do that with Spring and vaadin, but I currently try to have a solution without using Spring).

Thanks in advance

**Comment by marcelbaumann** [comment]
When publishing the question, I found the answer. The solution is to use "/erp/*.

Sorry for disturbing you.

**Comment by mvysny** [comment]
Hi Marcel, thank you for letting me know! No trouble - actually this is something that would be great to have documented. With your permission I'll reopen the bug and document this in the README.
